# Generated by Django 5.0.3 on 2024-09-06 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='completed',
        ),
    ]
