# Generated by Django 5.0.3 on 2024-09-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_shift_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
