# Generated by Django 5.1.1 on 2024-09-12 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_reportdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportData',
        ),
    ]
