# Generated by Django 5.1.1 on 2024-09-13 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_reportdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_type',
        ),
        migrations.RemoveField(
            model_name='report',
            name='start_time',
        ),
    ]
