# Generated by Django 5.0.3 on 2024-09-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
    ]
