# Generated by Django 5.0.3 on 2024-09-02 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oda', '0003_ceo_order_ceo_manager_order_manager_waiter_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ceo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.ceo'),
        ),
        migrations.RemoveField(
            model_name='manager',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.manager'),
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='waiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.waiter'),
        ),
        migrations.DeleteModel(
            name='CEO',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='Waiter',
        ),
    ]
