# Generated by Django 5.0.3 on 2024-09-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oda', '0006_order_sender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='manager_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
