# Generated by Django 5.0.3 on 2024-09-05 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oda', '0008_order_waiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='waiter',
        ),
    ]
