# Generated by Django 5.0.3 on 2024-09-05 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oda', '0009_remove_order_waiter'),
        ('users', '0002_waiter_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_waiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.waiter'),
        ),
    ]
