# Generated by Django 5.0.3 on 2024-09-06 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oda', '0010_order_assigned_waiter'),
        ('users', '0003_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.shift'),
        ),
    ]
