# Generated by Django 5.1.1 on 2024-09-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oda', '0011_order_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
