# Generated by Django 5.1.1 on 2024-09-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_menuitem_slug'),
        ('users', '0009_remove_report_end_time_remove_report_report_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='reports',
            field=models.ManyToManyField(blank=True, related_name='expenses', to='users.report'),
        ),
    ]
