# Generated by Django 5.1.1 on 2024-09-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_expense_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
